# Generated by Django 3.1 on 2022-08-20 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Comment text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('comments', models.ManyToManyField(related_name='commented_posts', through='photo_gallery.Comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
